#!/usr/bin/env python3
"""
generate_seed.py -- regenerate seed_data.sql with a big demo dataset.

Produces:
  * 50 students (33 male + 17 female), mostly allocated to rooms
  * 2 hostels and enough rooms to seat them
  * ~2.5 months of daily attendance (2026-06-01 .. 2026-08-11)
    for every student and all 3 staff members
  * A realistic spread of complaints, feedback, invoices, mess-off
    requests, in/out records, visitors, parcels, violations and menu.

Run:  python scripts/generate_seed.py
Writes: seed_data.sql  (overwrites the current file)

NOTE: student123 is the shared scrypt for ALL students here (same as the
old seed). Logins: student1..student50 / student123.
"""

import random
from datetime import date, timedelta

OUT = "seed_data.sql"

HASH_STUDENT = "scrypt:32768:8:1$dHF9S6ravzQbODud$7723829848ee0605439e56da915d58d7b7a367f308a99f8b387afc960c1d110ad19b88aa851ec4bc55c7ed7b8eda9633df35a8b19e5130284ca844a31980db9d"
HASH_STAFF = "scrypt:32768:8:1$ueps82YvEwUsZejm$c78857c37c492e6d397829e38db021ad62216d0b100661db99e719fd32043f2c005e49c54d4643da12817f6ef97e1aec7e713560a45f2e647651b1690ed46a2b"
HASH_MANAGER = "scrypt:32768:8:1$ItNtyupaUcH625hR$ec8438bf1d1dfa39c537087dbcc24ea6aa9c973e75cb1ec129ddc35a0e435822da3c837a8dca62cb58e06faa7added134f14fdcfd770664b449d3884bcd32c5c"

MALE_NAMES = [
    "Rafi Ahmed", "Tanvir Hasan", "Mehedi Karim", "Arif Chowdhury", "Shakib Khan",
    "Imran Hossain", "Farhan Rahman", "Nabil Islam", "Rakib Uddin", "Sabbir Ahmed",
    "Moin Uddin", "Shawon Mia", "Nayeem Islam", "Rifat Hossain", "Shuvo Das",
    "Tuhin Ahmed", "Rony Rahman", "Abdullah Al Mamun", "Jahid Hasan", "Sohel Rana",
    "Ashikur Rahman", "Bappi Hossain", "Fahim Shahriar", "Golam Kibria", "Habib Ullah",
    "Iftekhar Alam", "Jakir Hossain", "Kawsar Ahmed", "Mahfuzur Rahman", "Nazmul Hasan",
    "Omar Faruk", "Pavel Hossain", "Rashedul Islam",
]
FEMALE_NAMES = [
    "Sadia Islam", "Nusrat Jahan", "Farzana Akter", "Tanjila Rahman", "Mim Akter",
    "Rumana Ahmed", "Sharmin Sultana", "Nishat Tasnim", "Jannatul Ferdous", "Marufa Islam",
    "Sathi Rani", "Taslima Khatun", "Urmi Akter", "Sabrina Rahman", "Popy Islam",
    "Nadia Sultana", "Rima Chowdhury",
]
CITIES = ["Dhaka", "Chattogram", "Sylhet", "Rajshahi", "Khulna", "Barishal", "Rangpur", "Mymensingh", "Comilla", "Bogra"]

rng = random.Random(20260812)


def w(sql):
    out.append(sql + "\n")


def datetime_combine(d, hour):
    return d, hour


out = []
w("-- =====================================================================")
w("-- Seed data for the Hostel Management System (generated by scripts/generate_seed.py)")
w("-- Logins:")
w("--   manager   / admin123   (Manager)")
w("--   staff1-3  / staff123   (Staff)")
w("--   student1..%d / student123 (Students, shared password)" % (len(MALE_NAMES) + len(FEMALE_NAMES)))
w("-- =====================================================================")
w("-- DATA ONLY. Requires hostel_management_schema.sql to be imported first.")
w("-- Do not run twice without dropping the database (fixed IDs -> duplicate errors).")
w("-- =====================================================================")
w("USE hostel_management;")

# ---------------------------------------------------------------- USERS
w("-- USERS (passwords are scrypt hashes generated with werkzeug)")
rows = ["(1, 'manager',  '%s', 'manager')" % HASH_MANAGER]
for i in range(1, 4):
    rows.append("(%d, 'staff%d',   '%s', 'staff')" % (i + 1, i, HASH_STAFF))
n = 0
for i, name in enumerate(MALE_NAMES + FEMALE_NAMES, start=1):
    rows.append("(%d, 'student%d', '%s', 'student')" % (len(rows) + 1, i, HASH_STUDENT))
    n += 1
w("INSERT INTO users (user_id, username, password, role) VALUES")
w(",\n".join(rows) + ";")

# ---------------------------------------------------------------- MANAGERS
w("")
w("-- MANAGERS")
w("INSERT INTO managers (manager_id, user_id, name, designation) VALUES")
w("(1, 1, 'Ayesha Rahman', 'Chief Manager');")

# ---------------------------------------------------------------- STAFF
w("")
w("-- STAFF (designation values, per class diagram decision)")
w("INSERT INTO staff (staff_id, staff_no, user_id, name, designation, salary) VALUES")
w("(1, 'STF-0001', 2, 'Karim Mia',     'Caretaker', 15000.00),")
w("(2, 'STF-0002', 3, 'Rashida Begum', 'Cook',      12000.00),")
w("(3, 'STF-0003', 4, 'Hanif Uddin',   'Guard',     10000.00);")

# ---------------------------------------------------------------- HOSTELS / ROOMS
# Room plan (30 male beds used across 8 rooms, room 302 spare; 15 female beds used, 1 spare)
#   Main Hostel (Male): 101(4) 102(4) 103(4) 104(4) 201(4) 202(4) 203(4) 301(2) 302(2)
#   Girls Hostel (Female): 401(4) 402(4) 501(4) 502(4)
MALE_ROOMS = [("101", 4), ("102", 4), ("103", 4), ("104", 4), ("201", 4), ("202", 4), ("203", 4), ("301", 2), ("302", 2)]
FEMALE_ROOMS = [("401", 4), ("402", 4), ("501", 4), ("502", 4)]

# ----------------------------------------------------------------- STUDENTS
# Allocation plan:
#   males 1..30 -> 101(4) 102(4) 103(4) 104(4) 201(4) 202(4) 203(4) 301(2)  ; males 31..33 stay unallocated
#   females 1..15 -> 401(4) 402(4) 501(4) 502(3) ; females 16..17 stay unallocated
male_rooms_flat = [("101", 4), ("102", 4), ("103", 4), ("104", 4), ("201", 4), ("202", 4), ("203", 4), ("301", 2)]
female_rooms_flat = [("401", 4), ("402", 4), ("501", 4), ("502", 4)]

# build room_id per room_no
room_id_by_no = {no: rid for rid, (no, cap) in enumerate([x for x in MALE_ROOMS] + [x for x in FEMALE_ROOMS], start=1)}

male_seat = []
for no, cap in male_rooms_flat:
    male_seat.extend([no] * cap)
female_seat = []
for no, cap in female_rooms_flat:
    female_seat.extend([no] * cap)
male_seat = male_seat[:30]
female_seat = female_seat[:15]

import collections
occ = collections.Counter(room_id_by_no[no] for no in male_seat)
occ.update(room_id_by_no[no] for no in female_seat)

w("")
w("-- HOSTELS & ROOMS (varied capacities)")
w("INSERT INTO hostels (hostel_id, hostel_name, location, gender, total_rooms, lat, lng, radius_m) VALUES")
w("(1, 'Main Hostel',  'North Campus', 'Male',   %d, 23.8100000, 90.4125000, 50)," % len(MALE_ROOMS))
w("(2, 'Girls Hostel', 'South Campus', 'Female', %d, 23.8140000, 90.4160000, 50);" % len(FEMALE_ROOMS))

w("")
w("INSERT INTO rooms (room_id, hostel_id, room_no, total_beds, available_beds) VALUES")
room_rows = []
mid = 1
for no, cap in MALE_ROOMS:
    avail = cap - occ.get(mid, 0)
    room_rows.append("(%d, 1, '%s', %d, %d)" % (mid, no, cap, avail))
    mid += 1
for no, cap in FEMALE_ROOMS:
    avail = cap - occ.get(mid, 0)
    room_rows.append("(%d, 2, '%s', %d, %d)" % (mid, no, cap, avail))
    mid += 1
w(",\n".join(room_rows) + ";")

male_names = MALE_NAMES[:]
female_names = FEMALE_NAMES[:]
rng.shuffle(male_names)
rng.shuffle(female_names)

w("")
w("-- STUDENTS (50 total: %d male + %d female; 38 allocated, 12 unallocated)" % (len(male_names), len(female_names)))
alloc_m = 30
alloc_f = 15
sid = 1
st_rows = []
user_start = 5  # manager=1, staff1-3 = 2..4
user_id = user_start


def seat_for(name, gender, idx, alloc_count, seat_list):
    if idx < alloc_count:
        room_no = seat_list[idx]
        return room_id_by_no[room_no]
    return "NULL"


for idx, name in enumerate(male_names):
    rid = seat_for(name, "Male", idx, alloc_m, male_seat)
    room_sql = str(rid) if rid is not None else "NULL"
    email = name.lower().replace(" ", ".").replace("'", "") + "@example.com"
    phone = "017%08d" % (10000000 + sid)
    addr = rng.choice(CITIES)
    st_rows.append("(%d, 'STU-%04d', %d, '%s', '%s', '%s', '%s', 'Male',   %s)" %
                   (sid, sid, user_id, name.replace("'", "''"), email, phone, addr, room_sql))
    sid += 1
    user_id += 1

for idx, name in enumerate(female_names):
    rid = seat_for(name, "Female", idx, alloc_f, female_seat)
    room_sql = str(rid) if rid is not None else "NULL"
    email = name.lower().replace(" ", ".").replace("'", "") + "@example.com"
    phone = "017%08d" % (10000000 + sid)
    addr = rng.choice(CITIES)
    st_rows.append("(%d, 'STU-%04d', %d, '%s', '%s', '%s', '%s', 'Female', %s)" %
                   (sid, sid, user_id, name.replace("'", "''"), email, phone, addr, room_sql))
    sid += 1
    user_id += 1

w("INSERT INTO students (student_id, student_no, user_id, name, email, phone, address, gender, room_id) VALUES")
w(",\n".join(st_rows) + ";")

# ---------------------------------------------------------------- MESS MENU
w("")
w("-- MESS MENU (full week)")
days = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
meals = ["Breakfast", "Lunch", "Dinner"]
menus = {
    ("Saturday", "Breakfast"): "Paratha, Dal, Egg, Tea",
    ("Saturday", "Lunch"):     "Rice, Chicken Curry, Salad",
    ("Saturday", "Dinner"):    "Rice, Fish Fry, Vegetable",
    ("Sunday", "Breakfast"):   "Khichuri, Pickle, Tea",
    ("Sunday", "Lunch"):       "Rice, Beef Bhuna, Salad",
    ("Sunday", "Dinner"):      "Rice, Vegetable Curry, Egg",
    ("Monday", "Breakfast"):   "Ruti, Vorta, Tea",
    ("Monday", "Lunch"):       "Rice, Mutton Curry, Salad",
    ("Monday", "Dinner"):      "Rice, Fried Chicken, Dal",
    ("Tuesday", "Breakfast"):  "Paratha, Halim, Tea",
    ("Tuesday", "Lunch"):      "Rice, Chicken Roast, Salad",
    ("Tuesday", "Dinner"):     "Rice, Fish Curry, Vegetable",
    ("Wednesday", "Breakfast"): "Bread, Jam, Egg, Chai",
    ("Wednesday", "Lunch"):    "Rice, Beef Curry, Salad",
    ("Wednesday", "Dinner"):   "Rice, Prawn Fry, Dal",
    ("Thursday", "Breakfast"): "Khichuri, Begun Bhaja, Tea",
    ("Thursday", "Lunch"):     "Rice, Chicken Korma, Salad",
    ("Thursday", "Dinner"):    "Rice, Vegetable Pulao, Egg",
    ("Friday", "Breakfast"):   "Halwa, Puri, Chai",
    ("Friday", "Lunch"):       "Rice, Tehari, Salad",
    ("Friday", "Dinner"):      "Rice, Chicken Fry, Vegetable",
}
w("INSERT INTO mess_menu (menu_id, manager_id, day_of_week, meal_type, items_description) VALUES")
menu_rows = []
mi = 1
for d in days:
    for m in meals:
        menu_rows.append("(%d, 1, '%s', '%s', '%s')" % (mi, d, m, menus[(d, m)]))
        mi += 1
w(",\n".join(menu_rows) + ";")

# ---------------------------------------------------------------- ATTENDANCE GENERATOR
def gen_attendance():
    start = date(2026, 6, 1)
    end = date(2026, 8, 11)
    days = []
    d = start
    while d <= end:
        days.append(d)
        d += timedelta(days=1)

    rows_s = []
    aid = 1
    for si in range(1, 51):
        for d in days:
            r = rng.random()
            if r < 0.80:
                status = "Present"
            elif r < 0.90:
                status = "Absent"
            else:
                status = "Leave"
            rows_s.append("(%d, %d, '%s', '%s')" % (aid, si, d.isoformat(), status))
            aid += 1
    return rows_s


att_rows = gen_attendance()
w("")
w("-- STUDENT ATTENDANCE (daily, 2026-06-01 .. 2026-08-11) — %d rows" % len(att_rows))
w("INSERT INTO student_attendance (attendance_id, student_id, date, status) VALUES")
w(",\n".join(att_rows) + ";")

# ---------------------------------------------------------------- STAFF ATTENDANCE
staff_start = date(2026, 6, 1)
staff_end = date(2026, 8, 11)
staff_days = []
d = staff_start
while d <= staff_end:
    staff_days.append(d)
    d += timedelta(days=1)
staff_rows = []
said = 1
for sidx in range(1, 4):
    for d in staff_days:
        r = rng.random()
        if r < 0.85:
            status = "Present"
        elif r < 0.93:
            status = "Absent"
        else:
            status = "Leave"
        staff_rows.append("(%d, %d, '%s', '%s')" % (said, sidx, d.isoformat(), status))
        said += 1
w("")
w("-- STAFF ATTENDANCE (daily) — %d rows" % len(staff_rows))
w("INSERT INTO staff_attendance (attendance_id, staff_id, date, status) VALUES")
w(",\n".join(staff_rows) + ";")

# ---------------------------------------------------------------- INVOICES
w("")
w("-- INVOICES (Room Rent monthly for allocated students + a few extras)")
inv_rows = []
iid = 1
for si in range(1, 51):
    inv_rows.append("(%d, %d, 'Room Rent', 4500.00, '2026-07-01', 'Paid')" % (iid, si)); iid += 1
    inv_rows.append("(%d, %d, 'Room Rent', 4500.00, '2026-08-01', %s)" % (iid, si, "'Paid'" if rng.random() < 0.6 else "'Unpaid'")); iid += 1
    if rng.random() < 0.35:
        inv_rows.append("(%d, %d, 'Electricity', %.2f, '2026-08-15', %s)" % (iid, si, rng.choice([650, 720, 810, 900, 980]), rng.choice(["'Paid'", "'Unpaid'", "'Overdue'"]))); iid += 1
w("INSERT INTO invoices (invoice_id, student_id, invoice_type, amount, due_date, payment_status) VALUES")
w(",\n".join(inv_rows) + ";")

# ---------------------------------------------------------------- COMPLAINTS
w("")
w("-- COMPLAINTS")
complaint_pool = [
    "The bathroom tap is leaking since yesterday.",
    "The window lock is broken, room cannot be secured.",
    "Water heater is not working in the shared bath.",
    "Ceiling fan making a loud noise.",
    "Light bulb in the corridor is not working.",
    "The washroom drain is blocked.",
    "The AC unit is dripping water.",
    "Bed frame is shaky and noisy.",
    "The corridor is dusty and needs cleaning.",
    "The room door lock is jammed.",
    "Socket outlet is sparking when I plug in my charger.",
    "The water pressure in the shower is too low.",
    "Mosquitoes are getting in from a broken window mesh.",
    "The refrigerator in the common area is leaking.",
    "The Wi-Fi router in my room keeps disconnecting.",
]
comp_rows = []
cid = 1
for i in range(28):
    si = rng.randint(1, 50)
    d = date(2026, 6, 1) + timedelta(days=rng.randint(0, 71))
    status = rng.choice(["Pending", "Pending", "In Progress", "Resolved", "Resolved"])
    desc = rng.choice(complaint_pool)
    comp_rows.append("(%d, %d, NULL, '%s', '%s', '%s')" % (cid, si, desc.replace("'", "''"), status, d.isoformat()))
    cid += 1
w("INSERT INTO complaints (complaint_id, student_id, room_id, description, status, date) VALUES")
w(",\n".join(comp_rows) + ";")

# ---------------------------------------------------------------- FEEDBACK
w("")
w("-- FEEDBACK")
fb_pool = [
    "Food quality has been good this week.",
    "Dinner portions feel a little small.",
    "Washroom cleanliness needs more attention.",
    "WiFi speed is great, thank you.",
    "Mess food variety could be better.",
    "The common room is a nice place to hang out.",
    "Please add more power outlets in the study room.",
    "Night guard is very helpful.",
]
fb_rows = []
fid = 1
for i in range(25):
    si = rng.randint(1, 50)
    d = date(2026, 6, 5) + timedelta(days=rng.randint(0, 67))
    fb_rows.append("(%d, %d, '%s', '%s')" % (fid, si, rng.choice(fb_pool).replace("'", "''"), d.isoformat()))
    fid += 1
w("INSERT INTO feedback (feedback_id, student_id, description, date) VALUES")
w(",\n".join(fb_rows) + ";")

# ---------------------------------------------------------------- MESS OFF
w("")
w("-- MESS OFF REQUESTS")
mo_rows = []
moid = 1
for i in range(15):
    si = rng.randint(1, 50)
    start = date(2026, 6, 5) + timedelta(days=rng.randint(0, 60))
    end = start + timedelta(days=rng.randint(2, 7))
    status = rng.choice(["Pending", "Pending", "Approved", "Approved", "Rejected"])
    mo_rows.append("(%d, %d, '%s', '%s', '%s')" % (moid, si, start.isoformat(), end.isoformat(), status))
    moid += 1
w("INSERT INTO mess_off_requests (mess_off_id, student_id, start_date, end_date, status) VALUES")
w(",\n".join(mo_rows) + ";")

# ---------------------------------------------------------------- VISITORS
w("")
w("-- VISITORS")
vis_names = ["Ali Khan", "Rahim Uddin", "Fatema Akter", "Kamal Hossain", "Sumon Mia",
             "Rezaul Karim", "Nargis Begum", "Salman Farsi", "Mita Rani", "Anisur Rahman"]
vis_rows = []
vid = 1
for i in range(18):
    si = rng.randint(1, 50)
    st = rng.randint(1, 3)
    d = date(2026, 6, 5) + timedelta(days=rng.randint(0, 67))
    vis_rows.append("(%d, %d, %d, '%s', '%s')" % (vid, si, st, rng.choice(vis_names), d.isoformat()))
    vid += 1
w("INSERT INTO visitors (visitor_id, student_id, registered_by_staff, visitor_name, visit_date) VALUES")
w(",\n".join(vis_rows) + ";")

# ---------------------------------------------------------------- PARCELS
w("")
w("-- PARCELS")
par_status = ["Arrived", "Arrived", "Collected"]
par_rows = []
pid = 1
for i in range(20):
    si = rng.randint(1, 50)
    st = rng.randint(1, 3)
    rdate = date(2026, 6, 5) + timedelta(days=rng.randint(0, 67))
    status = rng.choice(par_status)
    if status == "Collected":
        cdate = rdate + timedelta(days=rng.randint(1, 4))
        collected_sql = "'%s 10:%02d:00', %d" % (cdate.isoformat(), rng.randint(0, 59), si)
    else:
        collected_sql = "NULL, NULL"
    par_rows.append("(%d, %d, %d, '%s', '%s', %s)" % (pid, si, st, status, rdate.isoformat(), collected_sql))
    pid += 1
w("INSERT INTO parcels (parcel_id, student_id, received_by_staff, status, received_date, collected_at, collected_by_student) VALUES")
w(",\n".join(par_rows) + ";")

# ---------------------------------------------------------------- VIOLATIONS
w("")
w("-- VIOLATIONS (Open + Resolved)")
vio_pool = [
    "Late night noise in the corridor.",
    "Unauthorized visitor after visiting hours.",
    "Smoking inside the room.",
    "Littering in the common area.",
    "Missing curfew without permission.",
    "Damage to hostel property.",
]
vio_rows = []
vid_ = 1
for i in range(12):
    si = rng.randint(1, 50)
    stf = rng.choice([None, None, 3])
    d = date(2026, 6, 5) + timedelta(days=rng.randint(0, 67))
    status = "Open" if rng.random() < 0.5 else "Resolved"
    resolved = "'%s'" % (d + timedelta(days=2)) if status == "Resolved" else "NULL"
    if stf is None:
        vio_rows.append("(%d, %d, NULL, '%s', '%s', '%s', %s, 1)" % (vid_, si, rng.choice(vio_pool).replace("'", "''"), d.isoformat(), status, resolved))
    else:
        vio_rows.append("(%d, NULL, %d, '%s', '%s', '%s', %s, 1)" % (vid_, stf, rng.choice(vio_pool).replace("'", "''"), d.isoformat(), status, resolved))
    vid_ += 1
w("INSERT INTO violations (violation_id, student_id, staff_id, description, date, status, resolved_at, recorded_by) VALUES")
w(",\n".join(vio_rows) + ";")

# ---------------------------------------------------------------- STUDENT IN / OUT
w("")
w("-- STUDENT IN / OUT")
reasons = ["Home visit", "Market trip", "Family function", "Doctor appointment", "Tuition class", "Movie night"]
io_rows = []
rid_ = 1
for i in range(22):
    si = rng.randint(1, 50)
    out_date = date(2026, 6, 5) + timedelta(days=rng.randint(0, 67))
    status = "Returned" if rng.random() < 0.7 else "Out"
    reason = rng.choice(reasons)
    if status == "Returned":
        in_dt = datetime_combine(out_date, rng.choice([17, 18, 19, 20, 21, 22, 23]))
        in_sql = "'%s %02d:%02d:00'" % (in_dt[0].isoformat(), in_dt[1], rng.randint(0, 59))
    else:
        in_sql = "NULL"
    out_hour = rng.choice([8, 9, 10, 11, 14, 15, 16])
    io_rows.append("(%d, %d, '%s %02d:00:00', %s, '%s', '%s')" %
                   (rid_, si, out_date.isoformat(), out_hour, in_sql, reason, status))
    rid_ += 1
w("INSERT INTO student_in_out (record_id, student_id, out_date, in_date, reason, status) VALUES")
w(",\n".join(io_rows) + ";")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out))


print("Wrote %s (%d lines)" % (OUT, len(out)))